import type { NextPage, GetServerSidePropsContext } from 'next';
import Head from 'next/head';

import nookies from 'nookies';
import { firebaseAdmin } from '../utils/firebaseAdmin';
import { getUserCourses } from '../utils/firebase';

import { useAuth } from '../context/AuthContext';

const Dashboard: NextPage = ({ courses }: any) => {
    const loggedUser = useAuth();

    courses = JSON.parse(courses);

    return (
        <div>
            <Head>
                <title>Dashboard - Course App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto px-5 md:p-0 md:w-10/12 lg:w-9/12 xl:w-3/4">
                <h1>Protected dashboard</h1>
                <h2 className="my-4">My courses</h2>
                <div className="flex">
                    {courses != [] &&
                        courses.map((course: any) => {
                            return (
                                <div
                                    key={course.name}
                                    className="p-5 border b-2 border-white/30 rounded relative"
                                >
                                    {/* eslint-disable-next-line @next/next/no-img-element */}
                                    <img
                                        src={course.videos[0].thumbnail}
                                        width="320"
                                        height="240"
                                        alt={course.videos[0].title}
                                    />
                                    <h1 className="font-medium mt-4 mb-1 cursor-pointer hover:underline">
                                        {course.name}
                                    </h1>
                                    <h2 className="text-white/90">
                                        {course.description}
                                    </h2>
                                    <h3 className="text-white/80">
                                        Videos count: {course.videos.length}
                                    </h3>
                                    <button className="button bg-red-600 px-2 py-1.5 absolute bottom-5 right-5">
                                        Remove
                                    </button>
                                </div>
                            );
                        })}
                </div>
            </main>
        </div>
    );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
    try {
        const cookies = nookies.get(ctx);
        const token = await firebaseAdmin.auth().verifyIdToken(cookies.token);

        // the user is authenticated!
        const { uid, email } = token;

        const coursesSnap = await getUserCourses(uid);

        let courses: any = [];
        coursesSnap.forEach((doc) => {
            courses.push(doc.data());
        });

        return {
            props: { courses: JSON.stringify(courses) }
        };
    } catch (err) {
        ctx.res.writeHead(302, { Location: '/' });
        ctx.res.end();

        return { props: {} as never };
    }
};

export default Dashboard;
