import type { NextPage, GetServerSidePropsContext } from 'next';
import Head from 'next/head';

import nookies from 'nookies';
import { firebaseAdmin } from '../utils/firebaseAdmin';

import { useAuth } from '../context/AuthContext';

const Dashboard: NextPage = () => {
    const loggedUser = useAuth();
    console.log(loggedUser);
    return (
        <div>
            <Head>
                <title>Dashboard - Course App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto px-5 md:p-0 md:w-10/12 lg:w-9/12 xl:w-3/4">
                <h1>Protected dashboard</h1>
            </main>
        </div>
    );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
    try {
        const cookies = nookies.get(ctx);
        const token = await firebaseAdmin.auth().verifyIdToken(cookies.token);

        // the user is authenticated!
        const { uid, email } = token;

        // FETCH STUFF HERE!! 🚀

        return {
            props: { message: `Your email is ${email} and your UID is ${uid}.` }
        };
    } catch (err) {
        ctx.res.writeHead(302, { Location: '/' });
        ctx.res.end();

        return { props: {} as never };
    }
};

export default Dashboard;
