import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Course App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto px-5 md:p-0 md:w-10/12 lg:w-9/12 xl:w-3/4">
                <h1>Course App 🚀🚀🚀</h1>

                <button className="button">Sign in</button>
                <button className="button-secondary">Sign up</button>
            </main>
        </div>
    );
};

export default Home;
