import type { NextPage } from 'next';
import Head from 'next/head';

import { useRouter } from 'next/router';

import { auth } from '../utils/firebase';
import { signOut } from 'firebase/auth';

const Home: NextPage = () => {
    const router = useRouter();

    const routerPush = async (href: string) => {
        await router.push(`/${href}`);
    };

    return (
        <div>
            <Head>
                <title>Course App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-auto px-5 md:p-0 md:w-10/12 lg:w-9/12 xl:w-3/4">
                <h1>Course App 🚀🚀🚀</h1>

                <div className="flex justify-center gap-4">
                    <button
                        className="button-secondary"
                        onClick={() => routerPush('signin')}
                    >
                        Sign in
                    </button>
                    <button
                        className="button"
                        onClick={() => routerPush('signup')}
                    >
                        Sign up
                    </button>
                </div>
            </main>
        </div>
    );
};

export default Home;
